<a href="https://colab.research.google.com/github/ElzatAhmed/machine-learning-notes/blob/main/first_attempt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# imports
%tensorflow_version 2.x  # this line is not required unless you are in a notebook
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


In [2]:
TRAIN_FEATURE_DIR = "/content/network_sample/train/features"
TRAIN_LABEL_DIR = "/content/network_sample/train/labels"
TEST_FEATURE_DIR = "/content/network_sample/test/features"
TEST_LABEL_DIR = "/content/network_sample/test/labels"

train_feature = np.zeros(shape=(500, 50, 50), dtype=float)
train_label = np.zeros(shape=(500, 50,), dtype=float)
test_feature = np.zeros(shape=(100, 50, 50), dtype=float)
test_label = np.zeros(shape=(100, 50,), dtype=float)

for i in range(500):
  path = f'{TRAIN_FEATURE_DIR}/f{i}.csv'
  df = pd.read_csv(path)
  train_feature[i] = df.values
  path = f'{TRAIN_LABEL_DIR}/l{i}.csv'
  df = pd.read_csv(path)
  train_label[i] = df.values

for i in range(100):
  path = f'{TEST_FEATURE_DIR}/f{i}.csv'
  df = pd.read_csv(path)
  train_feature[i] = df.values
  path = f'{TEST_LABEL_DIR}/l{i}.csv'
  df = pd.read_csv(path)
  test_label[i] = df.values

In [ ]:
train_feature

In [ ]:
train_label

In [6]:
train_feature.shape

(500, 50, 50)

In [7]:
train_label.shape

(500, 50)

In [4]:
train_feature = train_feature / 100
test_feature = test_feature / 100

In [9]:
# create the model
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(50, 50)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(50, activation='relu')
])

In [10]:
# compiling the model
model.compile(
    optimizer=tf.keras.optimizers.RMSprop(0.001),
    loss='mse',
    metrics=['mae', 'mse']
)

In [133]:
train_label[1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.])

In [11]:
result = model.predict(train_feature[:1])
result

array([[0.01115304, 0.        , 0.06126582, 0.10553794, 0.11645268,
        0.0397479 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.13365741, 0.04519689, 0.        , 0.03715605,
        0.        , 0.        , 0.03934497, 0.03627475, 0.0250033 ,
        0.03525222, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.06033648, 0.00758233, 0.11585291, 0.05441315,
        0.        , 0.        , 0.01715683, 0.14742722, 0.06351423,
        0.03941657, 0.18488221, 0.11112031, 0.        , 0.        ,
        0.        , 0.10216432, 0.02943389, 0.        , 0.03528717,
        0.02624935, 0.03264771, 0.        , 0.        , 0.07880899]],
      dtype=float32)

In [12]:
model.fit(train_feature, train_label, epochs=3)

Epoch 1/3
16/16 [==============================] - 1s 7ms/step - loss: 0.4356 - mae: 0.5488 - mse: 0.4356
Epoch 2/3
16/16 [==============================] - 0s 7ms/step - loss: 0.3419 - mae: 0.4550 - mse: 0.3419
Epoch 3/3
16/16 [==============================] - 0s 7ms/step - loss: 0.3383 - mae: 0.4508 - mse: 0.3383


In [13]:
model.evaluate(test_feature, test_label)

4/4 [==============================] - 0s 3ms/step - loss: 0.7687 - mae: 0.7880 - mse: 0.7687


[0.7686669826507568, 0.7880377173423767, 0.7686669826507568]

In [153]:
result = model.predict(test_feature)

In [157]:
result[5]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0002785 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00206684, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00030585],
      dtype=float32)